// Auto-generated by scripts/generate-region-ip-ui-data.js on 2025-12-28T08:20:52.483Z
// Source: https://azureiplookup-westus3.azurewebsites.net/api/serviceTagsByRegion

export interface RegionIpRangeEntry {
  regionId: string
  displayName: string
  regionGroup: string
  geography: string
  datacenterLocation: string
  serviceTagId: string
}

export const REGION_IP_RANGE_DIRECTORY: RegionIpRangeEntry[] = [
  {
    regionId: 'australiacentral',
    displayName: 'Australia Central',
    regionGroup: 'Australia and New Zealand',
    geography: 'Australia',
    datacenterLocation: 'Canberra',
    serviceTagId: 'AzureCloud.australiacentral'
  },
  {
    regionId: 'australiacentral2',
    displayName: 'Australia Central 2',
    regionGroup: 'Australia and New Zealand',
    geography: 'Australia',
    datacenterLocation: 'Canberra',
    serviceTagId: 'AzureCloud.australiacentral2'
  },
  {
    regionId: 'australiaeast',
    displayName: 'Australia East',
    regionGroup: 'Australia and New Zealand',
    geography: 'Australia',
    datacenterLocation: 'New South Wales',
    serviceTagId: 'AzureCloud.australiaeast'
  },
  {
    regionId: 'australiasoutheast',
    displayName: 'Australia Southeast',
    regionGroup: 'Australia and New Zealand',
    geography: 'Australia',
    datacenterLocation: 'Victoria',
    serviceTagId: 'AzureCloud.australiasoutheast'
  },
  {
    regionId: 'austriaeast',
    displayName: 'Austria East',
    regionGroup: 'Europe',
    geography: 'Austria',
    datacenterLocation: 'Vienna',
    serviceTagId: 'AzureCloud.austriaeast'
  },
  {
    regionId: 'belgiumcentral',
    displayName: 'Belgium Central',
    regionGroup: 'Western Europe',
    geography: 'Belgium',
    datacenterLocation: 'Brussels',
    serviceTagId: 'AzureCloud.belgiumcentral'
  },
  {
    regionId: 'brazilne',
    displayName: 'Brazil Northeast',
    regionGroup: 'South America',
    geography: 'Brazil',
    datacenterLocation: 'Fortaleza',
    serviceTagId: 'AzureCloud.brazilne'
  },
  {
    regionId: 'brazilsouth',
    displayName: 'Brazil South',
    regionGroup: 'South America',
    geography: 'Brazil',
    datacenterLocation: 'Sao Paulo State',
    serviceTagId: 'AzureCloud.brazilsouth'
  },
  {
    regionId: 'brazilse',
    displayName: 'Brazil Southeast',
    regionGroup: 'South America',
    geography: 'Brazil',
    datacenterLocation: 'Sao Paulo',
    serviceTagId: 'AzureCloud.brazilse'
  },
  {
    regionId: 'canadacentral',
    displayName: 'Canada Central',
    regionGroup: 'North America',
    geography: 'Canada',
    datacenterLocation: 'Toronto',
    serviceTagId: 'AzureCloud.canadacentral'
  },
  {
    regionId: 'canadaeast',
    displayName: 'Canada East',
    regionGroup: 'North America',
    geography: 'Canada',
    datacenterLocation: 'Quebec',
    serviceTagId: 'AzureCloud.canadaeast'
  },
  {
    regionId: 'centralfrance',
    displayName: 'Central France',
    regionGroup: 'Europe',
    geography: 'France',
    datacenterLocation: 'Paris',
    serviceTagId: 'AzureCloud.centralfrance'
  },
  {
    regionId: 'centralindia',
    displayName: 'Central India',
    regionGroup: 'Asia',
    geography: 'India',
    datacenterLocation: 'Pune',
    serviceTagId: 'AzureCloud.centralindia'
  },
  {
    regionId: 'centralus',
    displayName: 'Central US',
    regionGroup: 'North America',
    geography: 'United States',
    datacenterLocation: 'Iowa',
    serviceTagId: 'AzureCloud.centralus'
  },
  {
    regionId: 'centraluseuap',
    displayName: 'Central US (EUAP)',
    regionGroup: 'United States',
    geography: 'United States',
    datacenterLocation: 'Iowa',
    serviceTagId: 'AzureCloud.centraluseuap'
  },
  {
    regionId: 'chilec',
    displayName: 'Chile Central',
    regionGroup: 'South America',
    geography: 'Chile',
    datacenterLocation: 'Santiago',
    serviceTagId: 'AzureCloud.chilec'
  },
  {
    regionId: 'chinaeast',
    displayName: 'China East',
    regionGroup: 'China',
    geography: 'China',
    datacenterLocation: 'Shanghai',
    serviceTagId: 'AzureCloud.chinaeast'
  },
  {
    regionId: 'chinaeast2',
    displayName: 'China East 2',
    regionGroup: 'China',
    geography: 'China',
    datacenterLocation: 'Shanghai',
    serviceTagId: 'AzureCloud.chinaeast2'
  },
  {
    regionId: 'chinaeast3',
    displayName: 'China East 3',
    regionGroup: 'China',
    geography: 'China',
    datacenterLocation: 'Nantong',
    serviceTagId: 'AzureCloud.chinaeast3'
  },
  {
    regionId: 'chinanorth',
    displayName: 'China North',
    regionGroup: 'China',
    geography: 'China',
    datacenterLocation: 'Beijing',
    serviceTagId: 'AzureCloud.chinanorth'
  },
  {
    regionId: 'chinanorth2',
    displayName: 'China North 2',
    regionGroup: 'China',
    geography: 'China',
    datacenterLocation: 'Beijing',
    serviceTagId: 'AzureCloud.chinanorth2'
  },
  {
    regionId: 'chinanorth3',
    displayName: 'China North 3',
    regionGroup: 'China',
    geography: 'China',
    datacenterLocation: 'Zhangjiakou',
    serviceTagId: 'AzureCloud.chinanorth3'
  },
  {
    regionId: 'eastasia',
    displayName: 'East Asia',
    regionGroup: 'Asia',
    geography: 'Asia Pacific',
    datacenterLocation: 'Hong Kong',
    serviceTagId: 'AzureCloud.eastasia'
  },
  {
    regionId: 'eastus',
    displayName: 'East US',
    regionGroup: 'North America',
    geography: 'United States',
    datacenterLocation: 'Virginia',
    serviceTagId: 'AzureCloud.eastus'
  },
  {
    regionId: 'eastus2',
    displayName: 'East US 2',
    regionGroup: 'North America',
    geography: 'United States',
    datacenterLocation: 'Virginia',
    serviceTagId: 'AzureCloud.eastus2'
  },
  {
    regionId: 'eastus2euap',
    displayName: 'East US 2 (EUAP)',
    regionGroup: 'United States',
    geography: 'United States',
    datacenterLocation: 'Virginia',
    serviceTagId: 'AzureCloud.eastus2euap'
  },
  {
    regionId: 'germanyn',
    displayName: 'Germany North',
    regionGroup: 'Europe',
    geography: 'Germany',
    datacenterLocation: 'Berlin',
    serviceTagId: 'AzureCloud.germanyn'
  },
  {
    regionId: 'germanywc',
    displayName: 'Germany West Central',
    regionGroup: 'Europe',
    geography: 'Germany',
    datacenterLocation: 'Frankfurt',
    serviceTagId: 'AzureCloud.germanywc'
  },
  {
    regionId: 'indonesiacentral',
    displayName: 'Indonesia Central',
    regionGroup: 'Asia',
    geography: 'Indonesia',
    datacenterLocation: 'Jakarta',
    serviceTagId: 'AzureCloud.indonesiacentral'
  },
  {
    regionId: 'israelcentral',
    displayName: 'Israel Central',
    regionGroup: 'Middle East and Africa',
    geography: 'Israel',
    datacenterLocation: 'Israel',
    serviceTagId: 'AzureCloud.israelcentral'
  },
  {
    regionId: 'israelnorthwest',
    displayName: 'Israel Northwest',
    regionGroup: 'Middle East',
    geography: 'Israel',
    datacenterLocation: 'Tel Aviv',
    serviceTagId: 'AzureCloud.israelnorthwest'
  },
  {
    regionId: 'italynorth',
    displayName: 'Italy North',
    regionGroup: 'Europe',
    geography: 'Italy',
    datacenterLocation: 'Milan',
    serviceTagId: 'AzureCloud.italynorth'
  },
  {
    regionId: 'japaneast',
    displayName: 'Japan East',
    regionGroup: 'Asia',
    geography: 'Japan',
    datacenterLocation: 'Tokyo, Saitama',
    serviceTagId: 'AzureCloud.japaneast'
  },
  {
    regionId: 'japanwest',
    displayName: 'Japan West',
    regionGroup: 'Asia',
    geography: 'Japan',
    datacenterLocation: 'Osaka',
    serviceTagId: 'AzureCloud.japanwest'
  },
  {
    regionId: 'jioindiacentral',
    displayName: 'Jio India Central',
    regionGroup: 'Asia',
    geography: 'India',
    datacenterLocation: 'Nagpur',
    serviceTagId: 'AzureCloud.jioindiacentral'
  },
  {
    regionId: 'jioindiawest',
    displayName: 'Jio India West',
    regionGroup: 'Asia',
    geography: 'India',
    datacenterLocation: 'Jamnagar',
    serviceTagId: 'AzureCloud.jioindiawest'
  },
  {
    regionId: 'koreacentral',
    displayName: 'Korea Central',
    regionGroup: 'Asia',
    geography: 'Korea',
    datacenterLocation: 'Seoul',
    serviceTagId: 'AzureCloud.koreacentral'
  },
  {
    regionId: 'koreasouth',
    displayName: 'Korea South',
    regionGroup: 'Asia',
    geography: 'Korea',
    datacenterLocation: 'Busan',
    serviceTagId: 'AzureCloud.koreasouth'
  },
  {
    regionId: 'malaysiasouth',
    displayName: 'Malaysia South',
    regionGroup: 'Asia Pacific',
    geography: 'Malaysia',
    datacenterLocation: 'Johor Bahru',
    serviceTagId: 'AzureCloud.malaysiasouth'
  },
  {
    regionId: 'malaysiawest',
    displayName: 'Malaysia West',
    regionGroup: 'Asia',
    geography: 'Malaysia',
    datacenterLocation: 'Kuala Lumpur',
    serviceTagId: 'AzureCloud.malaysiawest'
  },
  {
    regionId: 'mexicocentral',
    displayName: 'Mexico Central',
    regionGroup: 'North America',
    geography: 'Mexico',
    datacenterLocation: 'Querétaro State',
    serviceTagId: 'AzureCloud.mexicocentral'
  },
  {
    regionId: 'newzealandnorth',
    displayName: 'New Zealand North',
    regionGroup: 'Australia and New Zealand',
    geography: 'New Zealand',
    datacenterLocation: 'Auckland',
    serviceTagId: 'AzureCloud.newzealandnorth'
  },
  {
    regionId: 'northcentralus',
    displayName: 'North Central US',
    regionGroup: 'North America',
    geography: 'United States',
    datacenterLocation: 'Illinois',
    serviceTagId: 'AzureCloud.northcentralus'
  },
  {
    regionId: 'northeurope',
    displayName: 'North Europe',
    regionGroup: 'Europe',
    geography: 'Europe',
    datacenterLocation: 'Ireland',
    serviceTagId: 'AzureCloud.northeurope'
  },
  {
    regionId: 'northeurope2',
    displayName: 'North Europe 2',
    regionGroup: 'Northern Europe',
    geography: 'Europe',
    datacenterLocation: 'Helsinki',
    serviceTagId: 'AzureCloud.northeurope2'
  },
  {
    regionId: 'norwaye',
    displayName: 'Norway East',
    regionGroup: 'Europe',
    geography: 'Norway',
    datacenterLocation: 'Oslo',
    serviceTagId: 'AzureCloud.norwaye'
  },
  {
    regionId: 'norwayw',
    displayName: 'Norway West',
    regionGroup: 'Europe',
    geography: 'Norway',
    datacenterLocation: 'Stavanger',
    serviceTagId: 'AzureCloud.norwayw'
  },
  {
    regionId: 'polandcentral',
    displayName: 'Poland Central',
    regionGroup: 'Europe',
    geography: 'Poland',
    datacenterLocation: 'Warsaw',
    serviceTagId: 'AzureCloud.polandcentral'
  },
  {
    regionId: 'qatarcentral',
    displayName: 'Qatar Central',
    regionGroup: 'Middle East and Africa',
    geography: 'Qatar',
    datacenterLocation: 'Doha',
    serviceTagId: 'AzureCloud.qatarcentral'
  },
  {
    regionId: 'eastus3',
    displayName: 'Region eastus3',
    regionGroup: 'Independent regions',
    geography: 'Global',
    datacenterLocation: '',
    serviceTagId: 'AzureCloud.eastus3'
  },
  {
    regionId: 'southafricanorth',
    displayName: 'South Africa North',
    regionGroup: 'Middle East and Africa',
    geography: 'South Africa',
    datacenterLocation: 'Johannesburg',
    serviceTagId: 'AzureCloud.southafricanorth'
  },
  {
    regionId: 'southafricawest',
    displayName: 'South Africa West',
    regionGroup: 'Middle East and Africa',
    geography: 'South Africa',
    datacenterLocation: 'Cape Town',
    serviceTagId: 'AzureCloud.southafricawest'
  },
  {
    regionId: 'southcentralus',
    displayName: 'South Central US',
    regionGroup: 'North America',
    geography: 'United States',
    datacenterLocation: 'Texas',
    serviceTagId: 'AzureCloud.southcentralus'
  },
  {
    regionId: 'southcentralus2',
    displayName: 'South Central US 2',
    regionGroup: 'United States',
    geography: 'United States',
    datacenterLocation: 'Texas',
    serviceTagId: 'AzureCloud.southcentralus2'
  },
  {
    regionId: 'southfrance',
    displayName: 'South France',
    regionGroup: 'Europe',
    geography: 'France',
    datacenterLocation: 'Marseille',
    serviceTagId: 'AzureCloud.southfrance'
  },
  {
    regionId: 'southindia',
    displayName: 'South India',
    regionGroup: 'Asia',
    geography: 'India',
    datacenterLocation: 'Chennai',
    serviceTagId: 'AzureCloud.southindia'
  },
  {
    regionId: 'southeastasia',
    displayName: 'Southeast Asia',
    regionGroup: 'Asia',
    geography: 'Asia Pacific',
    datacenterLocation: 'Singapore',
    serviceTagId: 'AzureCloud.southeastasia'
  },
  {
    regionId: 'southeastus',
    displayName: 'Southeast US',
    regionGroup: 'United States',
    geography: 'United States',
    datacenterLocation: 'Georgia',
    serviceTagId: 'AzureCloud.southeastus'
  },
  {
    regionId: 'southeastus3',
    displayName: 'Southeast US 3',
    regionGroup: 'United States',
    geography: 'United States',
    datacenterLocation: 'Georgia',
    serviceTagId: 'AzureCloud.southeastus3'
  },
  {
    regionId: 'spaincentral',
    displayName: 'Spain Central',
    regionGroup: 'Europe',
    geography: 'Spain',
    datacenterLocation: 'Madrid',
    serviceTagId: 'AzureCloud.spaincentral'
  },
  {
    regionId: 'swedencentral',
    displayName: 'Sweden Central',
    regionGroup: 'Europe',
    geography: 'Sweden',
    datacenterLocation: 'Gävle',
    serviceTagId: 'AzureCloud.swedencentral'
  },
  {
    regionId: 'swedensouth',
    displayName: 'Sweden South',
    regionGroup: 'Europe',
    geography: 'Sweden',
    datacenterLocation: 'Malmo',
    serviceTagId: 'AzureCloud.swedensouth'
  },
  {
    regionId: 'switzerlandn',
    displayName: 'Switzerland North',
    regionGroup: 'Europe',
    geography: 'Switzerland',
    datacenterLocation: 'Zurich',
    serviceTagId: 'AzureCloud.switzerlandn'
  },
  {
    regionId: 'switzerlandw',
    displayName: 'Switzerland West',
    regionGroup: 'Europe',
    geography: 'Switzerland',
    datacenterLocation: 'Geneva',
    serviceTagId: 'AzureCloud.switzerlandw'
  },
  {
    regionId: 'taiwannorth',
    displayName: 'Taiwan North',
    regionGroup: 'Asia Pacific',
    geography: 'Taiwan',
    datacenterLocation: 'Taipei',
    serviceTagId: 'AzureCloud.taiwannorth'
  },
  {
    regionId: 'taiwannorthwest',
    displayName: 'Taiwan Northwest',
    regionGroup: 'Asia Pacific',
    geography: 'Taiwan',
    datacenterLocation: 'Hsinchu',
    serviceTagId: 'AzureCloud.taiwannorthwest'
  },
  {
    regionId: 'uaecentral',
    displayName: 'UAE Central',
    regionGroup: 'Middle East and Africa',
    geography: 'UAE',
    datacenterLocation: 'Abu Dhabi',
    serviceTagId: 'AzureCloud.uaecentral'
  },
  {
    regionId: 'uaenorth',
    displayName: 'UAE North',
    regionGroup: 'Middle East and Africa',
    geography: 'UAE',
    datacenterLocation: 'Dubai',
    serviceTagId: 'AzureCloud.uaenorth'
  },
  {
    regionId: 'uksouth',
    displayName: 'UK South',
    regionGroup: 'Europe',
    geography: 'United Kingdom',
    datacenterLocation: 'London',
    serviceTagId: 'AzureCloud.uksouth'
  },
  {
    regionId: 'ukwest',
    displayName: 'UK West',
    regionGroup: 'Europe',
    geography: 'United Kingdom',
    datacenterLocation: 'Cardiff',
    serviceTagId: 'AzureCloud.ukwest'
  },
  {
    regionId: 'usgoviowa',
    displayName: 'US Gov Iowa',
    regionGroup: 'United States Government',
    geography: 'USGov',
    datacenterLocation: 'Iowa',
    serviceTagId: 'AzureCloud.usgoviowa'
  },
  {
    regionId: 'usstagec',
    displayName: 'US Stage Central',
    regionGroup: 'United States',
    geography: 'United States',
    datacenterLocation: 'Iowa',
    serviceTagId: 'AzureCloud.usstagec'
  },
  {
    regionId: 'usstagee',
    displayName: 'US Stage East',
    regionGroup: 'United States',
    geography: 'United States',
    datacenterLocation: 'Virginia',
    serviceTagId: 'AzureCloud.usstagee'
  },
  {
    regionId: 'usdodcentral',
    displayName: 'USDoD Central',
    regionGroup: 'United States',
    geography: 'USGov',
    datacenterLocation: 'Iowa',
    serviceTagId: 'AzureCloud.usdodcentral'
  },
  {
    regionId: 'usdodeast',
    displayName: 'USDoD East',
    regionGroup: 'United States',
    geography: 'USGov',
    datacenterLocation: 'Virginia',
    serviceTagId: 'AzureCloud.usdodeast'
  },
  {
    regionId: 'usgovarizona',
    displayName: 'USGov Arizona',
    regionGroup: 'United States',
    geography: 'USGov',
    datacenterLocation: 'Arizona',
    serviceTagId: 'AzureCloud.usgovarizona'
  },
  {
    regionId: 'usgovtexas',
    displayName: 'USGov Texas',
    regionGroup: 'United States',
    geography: 'USGov',
    datacenterLocation: 'Texas',
    serviceTagId: 'AzureCloud.usgovtexas'
  },
  {
    regionId: 'usgovvirginia',
    displayName: 'USGov Virginia',
    regionGroup: 'United States',
    geography: 'USGov',
    datacenterLocation: 'Virginia',
    serviceTagId: 'AzureCloud.usgovvirginia'
  },
  {
    regionId: 'westcentralus',
    displayName: 'West Central US',
    regionGroup: 'North America',
    geography: 'United States',
    datacenterLocation: 'Wyoming',
    serviceTagId: 'AzureCloud.westcentralus'
  },
  {
    regionId: 'westeurope',
    displayName: 'West Europe',
    regionGroup: 'Europe',
    geography: 'Europe',
    datacenterLocation: 'Netherlands',
    serviceTagId: 'AzureCloud.westeurope'
  },
  {
    regionId: 'westindia',
    displayName: 'West India',
    regionGroup: 'Asia',
    geography: 'India',
    datacenterLocation: 'Mumbai',
    serviceTagId: 'AzureCloud.westindia'
  },
  {
    regionId: 'westus',
    displayName: 'West US',
    regionGroup: 'North America',
    geography: 'United States',
    datacenterLocation: 'California',
    serviceTagId: 'AzureCloud.westus'
  },
  {
    regionId: 'westus2',
    displayName: 'West US 2',
    regionGroup: 'North America',
    geography: 'United States',
    datacenterLocation: 'Washington',
    serviceTagId: 'AzureCloud.westus2'
  },
  {
    regionId: 'westus3',
    displayName: 'West US 3',
    regionGroup: 'North America',
    geography: 'United States',
    datacenterLocation: 'Phoenix',
    serviceTagId: 'AzureCloud.westus3'
  }
]
