// Auto-generated by scripts/generate-hero-icons.mjs
export interface HeroIconPath {
  readonly d: string
  readonly fillRule?: string
  readonly clipRule?: string
  readonly strokeLinecap?: string
  readonly strokeLinejoin?: string
  readonly strokeWidth?: string
}

export interface HeroIconCircle {
  readonly type: 'circle'
  readonly cx: string
  readonly cy: string
  readonly r: string
  readonly strokeWidth?: string
}

export type HeroIconElement = HeroIconPath | HeroIconCircle

export interface HeroIconDefinition {
  readonly viewBox: string
  readonly elements: readonly HeroIconElement[]
}

export const HERO_ICON_DATA = {
  heroArrowDown: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M19.5 13.5 12 21m0 0-7.5-7.5M12 21V3',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroArrowDownTray: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroArrowTopRightOnSquare: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroArrowUpOnSquareStack: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M7.5 7.5h-.75A2.25 2.25 0 0 0 4.5 9.75v7.5a2.25 2.25 0 0 0 2.25 2.25h7.5a2.25 2.25 0 0 0 2.25-2.25v-7.5a2.25 2.25 0 0 0-2.25-2.25h-.75m0-3-3-3m0 0-3 3m3-3v11.25m6-2.25h.75a2.25 2.25 0 0 1 2.25 2.25v7.5a2.25 2.25 0 0 1-2.25 2.25h-7.5a2.25 2.25 0 0 1-2.25-2.25v-.75',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroArrowUpTray: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5m-13.5-9L12 3m0 0 4.5 4.5M12 3v13.5',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroArrowsRightLeft: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M7.5 21 3 16.5m0 0L7.5 12M3 16.5h13.5m0-13.5L21 7.5m0 0L16.5 12M21 7.5H7.5',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroBars3: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroBolt: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'm3.75 13.5 10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroBuildingOffice: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M3.75 21h16.5M4.5 3h15M5.25 3v18m13.5-18v18M9 6.75h1.5m-1.5 3h1.5m-1.5 3h1.5m3-6H15m-1.5 3H15m-1.5 3H15M9 21v-3.375c0-.621.504-1.125 1.125-1.125h3.75c.621 0 1.125.504 1.125 1.125V21',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroChartBar: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 0 1 3 19.875v-6.75ZM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V8.625ZM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V4.125Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroChevronDown: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'm19.5 8.25-7.5 7.5-7.5-7.5',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroChevronRight: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'm8.25 4.5 7.5 7.5-7.5 7.5',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroCloud: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M2.25 15a4.5 4.5 0 0 0 4.5 4.5H18a3.75 3.75 0 0 0 1.332-7.257 3 3 0 0 0-3.758-3.848 5.25 5.25 0 0 0-10.233 2.33A4.502 4.502 0 0 0 2.25 15Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroCloudArrowUp: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M12 16.5V9.75m0 0 3 3m-3-3-3 3M6.75 19.5a4.5 4.5 0 0 1-1.41-8.775 5.25 5.25 0 0 1 10.233-2.33 3 3 0 0 1 3.758 3.848A3.752 3.752 0 0 1 18 19.5H6.75Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroCodeBracket: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M17.25 6.75 22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3-4.5 16.5',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroCog6Tooth: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.325.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 0 1 1.37.49l1.296 2.247a1.125 1.125 0 0 1-.26 1.431l-1.003.827c-.293.241-.438.613-.43.992a7.723 7.723 0 0 1 0 .255c-.008.378.137.75.43.991l1.004.827c.424.35.534.955.26 1.43l-1.298 2.247a1.125 1.125 0 0 1-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.47 6.47 0 0 1-.22.128c-.331.183-.581.495-.644.869l-.213 1.281c-.09.543-.56.94-1.11.94h-2.594c-.55 0-1.019-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 0 1-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 0 1-1.369-.49l-1.297-2.247a1.125 1.125 0 0 1 .26-1.431l1.004-.827c.292-.24.437-.613.43-.991a6.932 6.932 0 0 1 0-.255c.007-.38-.138-.751-.43-.992l-1.004-.827a1.125 1.125 0 0 1-.26-1.43l1.297-2.247a1.125 1.125 0 0 1 1.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.086.22-.128.332-.183.582-.495.644-.869l.214-1.28Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      },
      {
        d: 'M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroCommandLine: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'm6.75 7.5 3 2.25-3 2.25m4.5 0h3m-9 8.25h13.5A2.25 2.25 0 0 0 21 18V6a2.25 2.25 0 0 0-2.25-2.25H5.25A2.25 2.25 0 0 0 3 6v12a2.25 2.25 0 0 0 2.25 2.25Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroExclamationCircle: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M12 9v3.75m9-.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 3.75h.008v.008H12v-.008Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroGlobeAlt: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M12 21a9.004 9.004 0 0 0 8.716-6.747M12 21a9.004 9.004 0 0 1-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 0 1 7.843 4.582M12 3a8.997 8.997 0 0 0-7.843 4.582m15.686 0A11.953 11.953 0 0 1 12 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0 1 21 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0 1 12 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 0 1 3 12c0-1.605.42-3.113 1.157-4.418',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroGlobeAmericas: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'm6.115 5.19.319 1.913A6 6 0 0 0 8.11 10.36L9.75 12l-.387.775c-.217.433-.132.956.21 1.298l1.348 1.348c.21.21.329.497.329.795v1.089c0 .426.24.815.622 1.006l.153.076c.433.217.956.132 1.298-.21l.723-.723a8.7 8.7 0 0 0 2.288-4.042 1.087 1.087 0 0 0-.358-1.099l-1.33-1.108c-.251-.21-.582-.299-.905-.245l-1.17.195a1.125 1.125 0 0 1-.98-.314l-.295-.295a1.125 1.125 0 0 1 0-1.591l.13-.132a1.125 1.125 0 0 1 1.3-.21l.603.302a.809.809 0 0 0 1.086-1.086L14.25 7.5l1.256-.837a4.5 4.5 0 0 0 1.528-1.732l.146-.292M6.115 5.19A9 9 0 1 0 17.18 4.64M6.115 5.19A8.965 8.965 0 0 1 12 3c1.929 0 3.716.607 5.18 1.64',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroInformationCircle: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'm11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroLockClosed: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M16.5 10.5V6.75a4.5 4.5 0 1 0-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 0 0 2.25-2.25v-6.75a2.25 2.25 0 0 0-2.25-2.25H6.75a2.25 2.25 0 0 0-2.25 2.25v6.75a2.25 2.25 0 0 0 2.25 2.25Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroMagnifyingGlass: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'm21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroMagnifyingGlassCircle: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'm15.75 15.75-2.489-2.489m0 0a3.375 3.375 0 1 0-4.773-4.773 3.375 3.375 0 0 0 4.774 4.774ZM21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroMap: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M9 6.75V15m6-6v8.25m.503 3.498 4.875-2.437c.381-.19.622-.58.622-1.006V4.82c0-.836-.88-1.38-1.628-1.006l-3.869 1.934c-.317.159-.69.159-1.006 0L9.503 3.252a1.125 1.125 0 0 0-1.006 0L3.622 5.689C3.24 5.88 3 6.27 3 6.695V19.18c0 .836.88 1.38 1.628 1.006l3.869-1.934c.317-.159.69-.159 1.006 0l4.994 2.497c.317.158.69.158 1.006 0Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroMapPin: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      },
      {
        d: 'M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1 1 15 0Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroPencilSquare: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'm16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroServerStack: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M5.25 14.25h13.5m-13.5 0a3 3 0 0 1-3-3m3 3a3 3 0 1 0 0 6h13.5a3 3 0 1 0 0-6m-16.5-3a3 3 0 0 1 3-3h13.5a3 3 0 0 1 3 3m-19.5 0a4.5 4.5 0 0 1 .9-2.7L5.737 5.1a3.375 3.375 0 0 1 2.7-1.35h7.126c1.062 0 2.062.5 2.7 1.35l2.587 3.45a4.5 4.5 0 0 1 .9 2.7m0 0a3 3 0 0 1-3 3m0 3h.008v.008h-.008v-.008Zm0-6h.008v.008h-.008v-.008Zm-3 6h.008v.008h-.008v-.008Zm0-6h.008v.008h-.008v-.008Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroShieldCheck: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M9 12.75 11.25 15 15 9.75m-3-7.036A11.959 11.959 0 0 1 3.598 6 11.99 11.99 0 0 0 3 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroSignal: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M9.348 14.652a3.75 3.75 0 0 1 0-5.304m5.304 0a3.75 3.75 0 0 1 0 5.304m-7.425 2.121a6.75 6.75 0 0 1 0-9.546m9.546 0a6.75 6.75 0 0 1 0 9.546M5.106 18.894c-3.808-3.807-3.808-9.98 0-13.788m13.788 0c3.808 3.807 3.808 9.98 0 13.788M12 12h.008v.008H12V12Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  },
  heroXMark: {
    viewBox: '0 0 24 24',
    elements: [
      {
        d: 'M6 18 18 6M6 6l12 12',
        strokeLinecap: 'round',
        strokeLinejoin: 'round'
      }
    ]
  }
} as const
