export const SystemPrompts = {
  // Code Assistant
  EXPLAIN_CODE: 'EXPLAIN_CODE',
  GENERATE_CODE: 'GENERATE_CODE',
  CONVERT_TO_BASH: 'CONVERT_TO_BASH',
  // Writing Assistant
  GENERATE_EMAIL: 'GENERATE_EMAIL',
  POLISH_TEXT: 'POLISH_TEXT',
  SUMMARIZE_TEXT: 'SUMMARIZE_TEXT',
  TRANSLATE_TEXT: 'TRANSLATE_TEXT'
}
